FROM node:14

# Create app directory
WORKDIR /app

# Install dependencies
COPY package*.json ./

RUN npm install

# Bundle app source
COPY . .
COPY .env.production .env

RUN npm run build

ENV NODE_ENV production

EXPOSE 8080
CMD ["node", "dist/index.js"]
USER node